CREATE TABLE IF NOT EXISTS `players` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Login` VARCHAR(50) NOT NULL DEFAULT '',
  `Game` CHAR(3) NOT NULL DEFAULT '',
  `NickName` VARCHAR(100) NOT NULL DEFAULT '',
  `playerID` VARCHAR(255) NOT NULL DEFAULT '',
  `Nation` CHAR(3) NOT NULL DEFAULT '',
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Wins` MEDIUMINT(9) NOT NULL DEFAULT 0,
  `TimePlayed` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `TeamName` CHAR(60) NOT NULL DEFAULT '',
  `LastSeen` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `Login` (`Login`),
  KEY `Game` (`Game`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
