CREATE TABLE IF NOT EXISTS `players_extra` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `cps` SMALLINT(5) NOT NULL DEFAULT -1,
  `dedicps` SMALLINT(5) NOT NULL DEFAULT -1,
  `donations` MEDIUMINT(9) UNSIGNED NOT NULL DEFAULT 0,
  `style` VARCHAR(20) NOT NULL DEFAULT '',
  `panels` VARCHAR(255) NOT NULL DEFAULT '',
  `playerID` VARCHAR(255) NOT NULL DEFAULT '',
  KEY `donations` (`donations`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
