CREATE TABLE IF NOT EXISTS `records` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ChallengeId` VARCHAR(255) NOT NULL DEFAULT '',
  `Times` LONGTEXT NOT NULL,
  `Date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Checkpoints` TEXT DEFAULT NULL,
  UNIQUE KEY `ChallengeId` (`ChallengeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
