CREATE TABLE IF NOT EXISTS `rs_rank` (
    `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `playerID` VARCHAR(255) NOT NULL DEFAULT '',
    `avg_score` DECIMAL(5,3) NOT NULL DEFAULT 0.000,
    UNIQUE (`playerID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
